version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: cybercare_project:${CYBERCARE_PROJECT_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      CYBERCARE_PROJECT_HOST: 0.0.0.0

#  propagator:
#    build:
#      context: .
#      dockerfile: ./deploy/propagator/Dockerfile
#    image: fastapi_cybercare_propagator-latest
#    restart: always
#    env_file:
#      - .env
#    depends_on:
#      - client
